### ISSUE TITLE
Unable to run on Snow Leopard 10.6.4

### ISSUE THREAD

**Issue by bdwilson** [godenzim/readernotifier#2]
I only get the exclamation icon.  Tried clearing cache file and removing plist.  Verified the credentials are correct.

**Comment by marforic** [comment]
fixed in latest 2.2.2, automatic update should pick it up!

**Comment by bdwilson** [comment]
Nice!  Auth problem appears fixed.  I have over 1000+ unread items and Notifier is only showing 2.  I'll mark all read and start over and see how things go.  Thanks!

Brian

**Comment by marforic** [comment]
1000 is a hard-limit imposed by google reader. let us know after a read-all

**Comment by bdwilson** [comment]
Seems to be picking up all items now.  The counter in the menu bar is not showing the correct number, however.  It currently shows 9 and there are many more than 9 items unread.

**Comment by bdwilson** [comment]
I'm still seeing inconsistent results as far as the number of items actually showing in the pull down.  It says 105 items at the top, but the pull down shows a dozen or so:  http://img.skitch.com/20100702-fsajpcggy74rw9at4cq5b7ftbg.jpg   Google Reader itself confirms that 105 is the correct number.

**Comment by marforic** [comment]
In the Preferences... -> General tab you can set how many items will show in the drop-down menu.

Regards

**Comment by bdwilson** [comment]
Sorry I wasn't clear, this is maxed out at 50 already.    It says "18" items now and is showing all 18 items, so it appears to sometimes properly show all the items, but other times the number of items show vs. the number listed in the menu bar are not anywhere close (if the number says 100+ I would expect to see 50 items listed, but I don't always see this).
